server:
  port: 7011
spring:
  application:
    name: jeecg-consumer
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml
      - optional:nacos:jeecg-consumer.yaml
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}